name: carbon_credits_app
description: Carbon tracker
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.66.2
  intl: ^0.19.0
  google_maps_flutter: ^2.7.0
  geolocator: ^14.0.2
  flutter_polyline_points: ^2.1.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true






